### ISSUE TITLE
Consider changing the v-icon to some sort of image.

### ISSUE THREAD

**Issue by thyrgle** [Zomis/minesweeper-flags-client#4]
`v-icon` does not support the `alt` attribute. The `alt` attribute allows me to hover my mouse over the button and figure out what it is supposed to do.

**Comment by Zomis** [comment]
Would this work? https://vuetifyjs.com/en/components/tooltips

**Comment by thyrgle** [comment]
Yeah, seems like a good idea to me.

**Comment by thyrgle** [comment]
See #6
