### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by neto112** [Zomis/minesweeper-flags-client#55]
I played on mobile with a friend to test if playing on a mobile device is good, so I have a suggestion for improving mobile responsiveness.

- [ ] Border-radius has a too thick thickness, making it difficult to read the block number.
- [ ] The game's width could be between 90% and 100%.
- [ ] Chat: Maybe could use v-lazy or v-textarea.
- [ ] Improve the visualization of v-card where there is a nickname, points, blick|bomb.

The image below shows how the screen looks on mobile devices.

![Imagem1](https://github.com/Zomis/minesweeper-flags-client/assets/79769515/53821cc2-09f2-462f-90cb-5fc5c676dacc)
![Imagem2](https://github.com/Zomis/minesweeper-flags-client/assets/79769515/ce070b9d-fac8-46dc-a780-8ac549d40286)

**Comment by Zomis** [comment]
Hi and thanks for your issue!

I agree that it could definitely need some improvement. I'm not very good at frontend design myself so any help you could give would be greatly appreciated!
